name: build
on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true
          cache: 'pnpm'

      - name: Build
        run: pnpm ng build --configuration production --base-href 'https://johnmeyer.dev/harmony-ts-demo/'