name: build
on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.27.1
          run_install: true

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm ng build -- --configuration production --base-href 'https://johnmeyer.dev/harmony-ts-demo/'