name: pages
on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.27.1
          run_install: true

      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm ng build -- --configuration production --base-href 'https://johnmeyer.dev/harmony-ts-demo/'

      - name: Commit Files
        run: |
          git checkout --orphan gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          find * -maxdepth 0 ! -name 'dist' -exec rm -r {} \;
          mv dist/* ./
          touch .nojekyll
          git add -A
          git commit -m "Update build"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Restore
        uses: actions/checkout@v1
